### ISSUE TITLE
Move helper functions in run.py to utils module

### ISSUE THREAD

**Issue by rabitt** [rabitt/motif#6]
Move [these functions](https://github.com/rabitt/motif/blob/master/motif/run.py#L100-L169) to a `utils.py` file, and add helper function that removes repeated code.

**Comment by rabitt** [comment]
@urinieto I think this has to stay in `run.py`. [These functions](https://github.com/rabitt/motif/blob/master/motif/run.py#L100-L169) require importing variables from `core.py`, and now `core.py` imports functions from `utils.py`, so we'd create a circular import :(

However I'll still break out the logic so that there isn't repeated code :)

**Comment by urinieto** [comment]
Oh, I see. Ok, no big thing! Looking good anyway :)
